'use strict'
const loadElements = (pageID, arr) => {
    const container = document.querySelector(pageID);
    arr.forEach(entry => { const section = document.createElement("section");
        const img = document.createElement("img");
        const h3 = document.createElement("h3");
        const p = document.createElement("p");
        const anchor = document.createElement('a');
        anchor.href = `https://duckduckgo.com/?q=\\${entry["name"]}+dublin&t=h_&ia=web`;
        h3.textContent = entry["name"];
        anchor.appendChild(h3);
        img.src = `images/adventure/${entry["id"]}.jpg`
        p.textContent = entry["desc"]; section.append(img, anchor, p);
        container.appendChild(section);
    });
}

const adventures = [
    {"id": 0, "name": "Dublin Under Sail", "desc": "Dublin Under Sail departs from Dún Laoghaire Marina, County Dublin, and allows you to experience life on board a traditional sailing vessel. Be a part of the crew, set the sails, heave the ropes, climb the rigging, and man the wheel. Enjoy the stunning beauty of Dublin’s iconic bay under the red-cloth sails of the Brian Boru."},
    {"id": 1, "name": "Wanderlust Irland - Belfast Tour From Dublin", "desc": "The North has become a must-see for any traveler and lover of Ireland. This tour enables you to focus on the beautiful city of Belfast, birthplace of the Titanic."},
    {"id": 2, "name": "Rural Adventure Tours", "desc": "Rural Adventure Tours, based in Cootehill, County Cavan, take visitors on private day and multi day tours into the heartlands of Ireland. Visitors can experience the beauty, culture, ancient stories, music and renowned pubs of Ireland as well as adventure activities."},
    {"id": 3, "name": "Cliffs Of Moher - Paddywagon Tours", "desc": "Visit the majestic Cliffs of Moher, one of the most spectacular cliffs in the world. Rising 820 ft above sea level, the cliffs give you an opportunity to take in breathtaking views of the Aran Islands and Galway Bay."},
    {"id": 4, "name": "HikeandClimb", "desc": "HikeandClimb based in County Dublin, is a provider of adventure, rock climbing and mountaineering skills for visitors to Ireland's Ancient East region. Their goal is to enable a personalised, tailored and original experience in suitable locations around the country."},
    {"id": 5, "name": "Irish Cycling Safaris", "desc": "Irish Cycling Safaris provide group self-guided cycling tours in Ireland, offering wonderful sights and charming accommodation. Bespoke and custom tours can be arranged. Cycling Safaris guarantee a fun and friendly experience to all types of cyclists."},
    {"id": 6, "name": "Dublin Wine Trails", "desc": "A wine trail around Dublin that is steeped in local flavour. Soak up the amazing atmosphere and enjoy what this cobble-stoned, charming city has to offer. Taste an exciting line up of wines and tapas style bites in a fun and social environment."},
    {"id": 7, "name": "Excursiones Irlanda - Giant’s Causeway Tour", "desc": "Now that you are in Ireland do not miss the chance to visit the legendary Giant´s Causeway! This tour includes the entrance fee for the Giant´s Causeway Visitor Center and you will be provided with free audio guides."},
    {"id": 8, "name": "Hollywood Lakes Golf Club", "desc": "Hollywood Lakes Golf Club is one of the best parkland golf clubs in Dublin. Measuring more than 6,600 yds, it boasts some of the most spectacular scenery overlooking Dublin and Lambay Island."},
    {"id": 9, "name": "Howth-Boats", "desc": "Howth-Boats are a boat hire and charter fishing service based on the West Pier in Howth, County Dublin."},
    {"id": 10, "name": "Wild N Happy Travel", "desc": "Experience the natural beauty and scenery of Ireland on an outstanding trip with Wild N Happy in Aghadoe, Co. Kerry. Join an adventure tour, explore the coast by bike or have some family friendly fun in incredible settings."},
    {"id": 11, "name": "A Spasso A Dublino - Italian Tour In Dublin", "desc": "A Spasso A Dublino - Italian Tour in Dublin provides Italian walking tours around the city, every day, 'Our Dublin' (10:00) and 'The Life of U2' (10:30). Tour Di Dublino A Piedi in Italiano - 'La Vostra Dublino' e 'La Vita Degli U2'."},
    {"id": 12, "name": "Cliffs Of Moher - Finn McCools Tours", "desc": "The Cliffs of Moher is the most popular day tour from Dublin. And also the most popular day tour in Ireland for a good reason: it is a spectacular sight not to be missed! Just sit back, relax and enjoy the best day tour with Finn McCools Tours."},
    {"id": 13, "name": "8 Day Wild Irish Rover - Vagabond Tours Of Ireland", "desc": "Its wild, it's Irish and its roving. The award winning 8 Day Wild Irish Rover - Vagabond Tours of Ireland includes a night in a castle, two nights in Dingle town and a great variety of activity options and historical sites for each day."},
    {"id": 14, "name": "Explorium", "desc": "Explorium is ideal for a family day out. A real 21st century hands-on experience where science and sport meet, with over 300 interactive exhibits designed to ignite curiosity in its visitors. For everyone age 2 years and up."},
    {"id": 15, "name": "Pat Liddy's Walking Tours Of Dublin Ltd", "desc": "Pat Liddy's Walking Tours of Dublin offer both scheduled and private walking tours of Dublin City. Historian Pat Liddy and his team of highly knowledgeable and enthusiastic guides will point out hidden gems and their stories, as well as the famous places. Starting points vary depending on the tour."},
    {"id": 16, "name": "The Rink At D12", "desc": "Dublin's Roller Disco, The Rink at D12. The 4,500 square foot roller disco is perfect for nights out with friends, children’s birthday parties or as a great way to keep fit."},
    {"id": 17, "name": "Irish Secret Sights", "desc": "Irish Secret Sights - Presentation of Ireland s most ancient and Haunted Castles in Ireland."},
    {"id": 18, "name": "Wicklow, Glendalough & Kilkenny Day Tour - Hilltoptreks", "desc": "Discover some of Ireland’s hidden gems in Ireland’s Ancient East on this day tour from Dublin City. Walk in the valley of Glendalough surrounded by nature and visit an Irish castle in Kilkenny City."},
    {"id": 19, "name": "Dublin Literary Pub Crawl", "desc": "Ranked number 4 in The World's 50 Best Walks by the Sunday Times, this is an award winning show that crawls from pub to pub with professional actors performing from the works of Dublin's most famous writers, Joyce, Beckett, Oscar Wilde, Brendan Behan and many more."},
    {"id": 20, "name": "Ralph Smyth Tours", "desc": "Have you ever wondered where Dublin city got its name from, where the Vikings lived in Dublin, which is the oldest church in the city, where were the city walls? If so, why not enjoy a fascinating two hour walking tour of the ancient heart of Dublin with a professional tour guide."},
    {"id": 21, "name": "Wanderlust Irland - Cliffs Of Moher Tour From Dublin", "desc": "Now that you are in Ireland do not miss the chance to visit the breathtaking Cliffs of Moher! This tour includes the entrance fee for the Cliffs of Moher Center. You will also enjoy a scenic drive along the Wild Atlantic Way Coast."},
    {"id": 22, "name": "GoQuest", "desc": "GoQuest, Carrickmines, County Dublin is a multi-challenge indoor arena of 27 rooms where groups of three to five persons compete against the clock. Each room consists of a light physical, mental or skill challenge. It is suitable for older children, teenagers and adults."},
    {"id": 23, "name": "U2'S Dublin - See Dublin By Bike", "desc": "U2's Dublin - a guided tour by bike of Dublin city. This tour makes particular reference to the places associated with the members of U2, one of the world's greatest rock bands that started here."},
    {"id": 24, "name": "Dublin Falconry", "desc": "Dublin Falconry is now situated in Luttrellstown Castle Resort in Dublin 15. Visitors learn the art of falconry, with flying displays and hands-on experiences. They cater for everyone including children and special-needs customers. Handle your hawk and get a selfie with it. They also offer Owl experiences for great memories."},
    {"id": 25, "name": "Wild Food Events", "desc": "Join Wild Food Events in Killiney, South County Dublin, for a wild food walk along the beautiful Killiney coastline. Discover the delicious wild edibles that grow all around us. Learn how to turn them into tasty treats, zingy cocktails and simple home remedies."},
    {"id": 26, "name": "Prestige Chauffeur Ltd.", "desc": "Prestige Chauffeur Ltd. is a luxury transport service based in Dublin ."},
    {"id": 27, "name": "Wanderlust Irland - Wicklow, Kilkenny & Glendalough Tour From Dublin", "desc": "Depart Dublin for this award winning and brilliant day trip with your 100% Irish Tour Guide and travel through the beautiful countryside of County Wicklow until we arrive in Glendalough."},
    {"id": 28, "name": "Touristy Ireland", "desc": "Touristy Ireland offer private guided tours all around Ireland. Get the most from your day by creating a customised tour plan that is perfectly suited to your needs. See all of Dublin in one day or visit Glendalough and Powerscourt in a half day."},
    {"id": 29, "name": "WILDIRISH Motorcycle Tours", "desc": "WILDIRISH Motorcycle Tours of Ireland, Glenageary, County Dublin, are motorcycle tours that are designed to be fun. You can use your own motorcycle and ride at your own pace. All tours have a guided and self guided option with long or short route options."},
    {"id": 30, "name": "Activities Ireland", "desc": "Welcome to Activities Ireland. Here you'll find one of Ireland's leading ground-handling operator in golf breaks, golf tours, activity holidays and leisure breaks in Ireland, across Europe and abroad."},
    {"id": 31, "name": "Cronin's Coaches", "desc": "When you travel with Cronin's Coaches, you travel in high style. You can sit back and relax, not worrying about maps, directions or getting lost."},
    {"id": 32, "name": "The Ireland Whiskey Trail", "desc": "The award winning Ireland Whiskey Trail is a free touring guide to Ireland's distilleries, best whiskey pubs, hotel and golf club bars and specialised whiskey shops. It includes a free touring map in English, French and German."},
    {"id": 33, "name": "The Belfast Titanic Tour - Finn McCools Tours", "desc": "As the capital city of Northern Ireland, Belfast has a lot to offer. With tourism in Northern Ireland growing at a phenomenal pace, this day tour from Dublin truly shows you the best Northern Ireland has to offer in a day."},
    {"id": 34, "name": "The Galway Gravedigger Bus Tour - Hidden Dublin Walks And Tours", "desc": "The Galway Gravedigger Bus Tour provides a themed ghost bus tour with actor guides recounting tales of Galway's darker history. The tour includes a ghoulish drink in McHugh’s Bar."},
    {"id": 35, "name": "Rare Ireland Tours", "desc": "Explore the fascinating story of Ireland through themed walking tours with Rare Ireland Tours, Dublin. Explore Ireland's military heritage on the Dublin's Military Mile walking tour and the living story of Dublin, from Viking times to today, on the Loving the Liberties walking tour."},
    {"id": 36, "name": "Irish Welcome Tours", "desc": "Irish Welcome Tours is one of Ireland's leading incoming tour operators and destination management companies, in operation since 1989."},
    {"id": 37, "name": "Solve A Mystery", "desc": "Solve A Mystery is a mystery walking tour in Dublin City. This murder mystery trail is inspired by true events. As an investigator, it is your duty to solve the mysterious disappearance. You must gather sufficient evidence and find the right suspect to ensure the safety of Dublin City streets."},
    {"id": 38, "name": "Irlanda In Italiano", "desc": "Irlanda in Italiano provide Italian language tours to visitors to Ireland who do not have a proficient level of English."},
    {"id": 39, "name": "Escape Dublin", "desc": "Escape Dublin is a fun, challenging live escape game. Try the Witchcraft & Wizardry school, help Sherlock Holmes solve a mystery, or find the cure in the Contagion Rooms. Do you have what it takes to solve the clues and escape in 60 minutes?"},
    {"id": 40, "name": "Curran Golf", "desc": "Curran Golf is the gateway to your dream golf vacation in Ireland. Curran Golf are specialists in bespoke golf vacations and cater for your every need including tee times, accommodation, transport, club hire and anything else you may require."},
    {"id": 41, "name": "Executive Travel Solutions", "desc": "Executive Travel Solutions, based in County Galway, with offices also in Dublin City, offer private guided tours of Ireland with a full executive chauffeur service. Luxury mini coach hire can also be arranged. Sit back and relax in luxury vehicles, while being taken to your destination."},
    {"id": 42, "name": "Wicklow Day Tour - Coach Tours Of Ireland", "desc": "The Day Tour of Wicklow departs from Dublin daily, taking in the breathtaking scenery of the Wicklow Mountains, Glencree, Sally Gap, Lough Tay, Glendalough, The Meeting of the Waters and Avoca (Ballykissangel)."},
    {"id": 43, "name": "My Ireland Tour - Ancient Ireland Mini-Group Tour", "desc": "Live like royalty on a tour of Ireland that gets you closer to some of Ireland's best loved attractions. With only eight guests per tour, there is more time and freedom to explore your own interests."},
    {"id": 44, "name": "Private Giants Causeway Day Tour With Kennedy & Carr", "desc": "Discover Giants Causeway & Belfast on this private day tour from Dublin. Enjoy your own private tour vehicle and driver guide with collection from your Dublin hotel."},
    {"id": 45, "name": "Excursiones Irlanda - Cliffs Of Moher Day Tour", "desc": "Cliffs of Moher Day Tour From Dublin. Travel from the banks of Dublin´s river Liffey to Ireland´s Wild Atlantic Way and experience the biggest attraction in all of Ireland."},
    {"id": 46, "name": "Celts & Castles Tour - Hilltoptreks", "desc": "The Celts & Castles Tour from Dublin City with Hilltoptreks brings you to the counties of Meath and Louth. Hear stories and history from the first settlers in Ireland to the Celts, Vikings, Anglo-Normans, and up to the present day."},
    {"id": 47, "name": "Rosie's Jigs And Wigs", "desc": "Want to dress up like a 'reel' Irish dancer so you can channel your inner Michael Flatley? At Rosie's Jigs and Wigs, at The Hardcourt Hotel in Dublin City centre, try on the costumes, learn the basic Irish dancing steps and enjoy an Irish themed photoshoot."},
    {"id": 48, "name": "The Chocolate Warehouse", "desc": "The Chocolate Warehouse, in Walkinstown Dublin, is a family friendly venue where visitors can enjoy the story of chocolate with a hands on experience of making chocolates where you get to bring home your own creations. Happy memories!"},
    {"id": 49, "name": "Rabbie’s Small Group Tours", "desc": "Venture off the beaten track with Rabbie’s Tours of Ireland and discover the best of the Emerald Isle. You’ll join a small group tour of up to 16 people and explore all the country has to offer, from dramatic landscapes to spectacular traditions!"}
]

loadElements("#adventures", adventures);
