#firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"

x="Dublin Under Sail"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="Wanderlust Irland - Belfast Tour From Dublin"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="Rural Adventure Tours"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="Cliffs Of Moher - Paddywagon Tours"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="HikeandClimb"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="Irish Cycling Safaris"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="Dublin Wine Trails"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="Excursiones Irlanda - Giant’s Causeway Tour"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="Hollywood Lakes Golf Club"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="Howth-Boats"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="Wild N Happy Travel"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="A Spasso A Dublino - Italian Tour In Dublin"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="Cliffs Of Moher - Finn McCools Tours"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="8 Day Wild Irish Rover - Vagabond Tours Of Ireland"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="Explorium"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="Pat Liddy's Walking Tours Of Dublin Ltd"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="The Rink At D12"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="Irish Secret Sights"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="Wicklow Glendalough & Kilkenny Day Tour - Hilltoptreks"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="Dublin Literary Pub Crawl"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="Ralph Smyth Tours"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="Wanderlust Irland - Cliffs Of Moher Tour From Dublin"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="GoQuest"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="U2'S Dublin - See Dublin By Bike"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="Dublin Falconry"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="Wild Food Events"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="Prestige Chauffeur Ltd."; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="Wanderlust Irland - Wicklow Kilkenny & Glendalough Tour From Dublin"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="Touristy Ireland"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="WILDIRISH Motorcycle Tours"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="Activities Ireland"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="Cronin's Coaches"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="The Ireland Whiskey Trail"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="The Belfast Titanic Tour - Finn McCools Tours"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="The Galway Gravedigger Bus Tour - Hidden Dublin Walks And Tours"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="Rare Ireland Tours"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="Irish Welcome Tours"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="Solve A Mystery"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="Irlanda In Italiano"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="Escape Dublin"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="Curran Golf"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="Executive Travel Solutions"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="Wicklow Day Tour - Coach Tours Of Ireland"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="My Ireland Tour - Ancient Ireland Mini-Group Tour"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="Private Giants Causeway Day Tour With Kennedy & Carr"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="Excursiones Irlanda - Cliffs Of Moher Day Tour"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="Celts & Castles Tour - Hilltoptreks"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="Rosie's Jigs And Wigs"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="The Chocolate Warehouse"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"
x="Rabbie’s Small Group Tours"; firefox "https://duckduckgo.com/?q=$x&t=h_&iax=images&ia=images&iaf=layout%3AWide"


